Number input range min max limits not working as expected
FlowFuse/node-red-dashboard pull request #1273
Opened 2024-09-06 15:26 UTC by gayanSandamal

## Description

#### Min / Max limitation and Step

https://github.com/user-attachments/assets/4900230e-bc74-4d77-8150-a174f39b371a

#### Responsiveness

Note that I've hide icon and clear button when widget gets shrink and there is no room for the payload to display

https://github.com/user-attachments/assets/1f2dd84e-882b-48bf-a095-3adfedcdeaca

## Related Issue(s)

https://github.com/FlowFuse/node-red-dashboard/issues/1244

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-09-06 16:52 UTC, Steve-Mcl commented
@gayanSandamal can you also include built-in help update in `nodes/widgets/locales/en-US/ui_number_input.html`.
Please ensure all properties that support dynamic setting (either existing or added in this PR) are listed.
Ta.

2024-09-09 13:50 UTC, Steve-Mcl requested changes
This PR adds dynamic support for min, max, step but the nodes built-in help is not updated.

Please update `nodes/widgets/locales/en-US/ui_number_input.html` to reflect the dynamic support

2024-09-10 14:44 UTC, Steve-Mcl requested changes
Apart from the suggested text update to say "`msg.ui_update`" I noticed this...

https://github.com/FlowFuse/node-red-dashboard/pull/1273/files#diff-6c3a8b98faadfc018feafc6225a11d60436505ac049ee150485c575cdfc29e4eR192-R194

I dont think the `onChange` ↑ handler will work as expected when the `step` is > 1.

2024-09-11 04:35 UTC, gayanSandamal commented on nodes/widgets/locales/en-US/ui_number_input.html
>      <p>Any of the following can be appended to a <code>msg.</code> in order to override or set properties on this node at runtime.</p>
@Steve-Mcl you're correct I've updated the onChange logic [here](https://github.com/FlowFuse/node-red-dashboard/pull/1273/commits/fa699ac31734cbbb211c3c9051cd27f42a05bba0)

regarding the docs update I've noticed the same in [core-widgets.md](https://github.com/FlowFuse/node-red-dashboard/blob/a371146f7ac8a7c36c27714eb6a39ec214af69ff/docs/contributing/widgets/core-widgets.md?plain=1#L255)

<img width="1038" alt="Screenshot 2024-09-11 at 10 04 15" src="https://github.com/user-attachments/assets/6bc707fa-0393-405a-a3be-528b2d695ed9">

2024-09-11 10:50 UTC, joepavitt commented
<img width="537" alt="Screenshot 2024-09-11 at 11 50 29" src="https://github.com/user-attachments/assets/b8191b4d-b170-468e-bd84-63f177a18722">

Tried setting the step and min/max and get errors

2024-09-11 10:53 UTC, joepavitt commented
Enforcing the `controlVariant` to be stacked too isn't friendly for touchscreens, so please make this a configurable option for the Number Input itself

2024-09-11 11:10 UTC, Steve-Mcl commented
Additional issues...

1. Setting a negative step permits number to escape bounds (top number input in demo gif)
   1. Result is unpredictable. Either we support negative spin or add validation  
   3. Operating the spinner button permits the value to escape min/max
2. In some cases, operating keyboard up/down not possible (think it is related to step > 1, not sure)
3. In some cases, the spinner buoon is greyed out (see 4th spinner in gif) - max is 100 but spinner button is greyed


**IMPORTANT CLUE**
After injecting dynamic values for all props, everything appears to work correctly (except negative step)


Demo:
![chrome_dxBwBqVafK](https://github.com/user-attachments/assets/2faeb6a6-bdb0-48df-b42f-a930edcd02ef)


Demo flow:
```
[{"id":"cbdcfc6a2166b7ee","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"auto, min:0, max:10, step 1","order":14,"width":0,"height":0,"topic":"topic","topicType":"msg","min":0,"max":10,"step":1,"tooltip":"","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":false,"icon":"","iconPosition":"left","iconInnerPosition":"inside","x":2280,"y":1200,"wires":[[]]},{"id":"b04429265d510afe","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"2x1, min 0, max 10, step 1","order":16,"width":"2","height":"1","topic":"topic","topicType":"msg","min":0,"max":10,"step":1,"tooltip":"","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":false,"icon":"","iconPosition":"left","iconInnerPosition":"inside","x":2280,"y":1240,"wires":[[]]},{"id":"f977fa12fa24d0e9","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"6x1, min 0, max 9, step 3, icon+tooltip+clear","order":13,"width":"6","height":"1","topic":"topic","topicType":"msg","min":0,"max":"9","step":"3","tooltip":"6x1, min 0, max 9, step 3, icon+tooltip+clear","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":true,"icon":"cog","iconPosition":"left","iconInnerPosition":"inside","x":2330,"y":1280,"wires":[[]]},{"id":"4936b7f3448d30e8","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"6x1, min 0, max 15, step -5, icon+tooltip+clear","order":12,"width":"6","height":"1","topic":"topic","topicType":"msg","min":0,"max":"15","step":"-5","tooltip":"6x1, min 0, max 15, step -5, icon+tooltip+clear","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":true,"icon":"home","iconPosition":"left","iconInnerPosition":"outside","x":2340,"y":1320,"wires":[[]]},{"id":"bc628c01a00bc840","type":"inject","z":"f80624abfd69b02e","name":"dynamic","props":[{"p":"ui_update.step","v":"2","vt":"num"},{"p":"ui_update.min","v":"4","vt":"num"},{"p":"ui_update.max","v":"8","vt":"num"},{"p":"ui_update.icon","v":"check","vt":"str"},{"p":"ui_update.label","v":"fred","vt":"str"},{"p":"ui_update.clearable","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1960,"y":1220,"wires":[["c68b54d25a2dd6c8"]]},{"id":"c5c577944d07723b","type":"inject","z":"f80624abfd69b02e","name":"reset dynamic","props":[{"p":"ui_update.step","v":"null","vt":"json"},{"p":"ui_update.min","v":"null","vt":"json"},{"p":"ui_update.max","v":"null","vt":"json"},{"p":"ui_update.icon","v":"null","vt":"json"},{"p":"ui_update.label","v":"null","vt":"json"},{"p":"ui_update.clearable","v":"null","vt":"json"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1986,"y":1302,"wires":[["c68b54d25a2dd6c8"]]},{"id":"2394c0ef8e1b0431","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"auto, min 0, max 100, step 1","order":15,"width":0,"height":0,"topic":"topic","topicType":"msg","min":0,"max":"100","step":"1","tooltip":"Hello tooltip","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":false,"icon":"","iconPosition":"left","iconInnerPosition":"inside","x":2280,"y":1380,"wires":[[]]},{"id":"c68b54d25a2dd6c8","type":"junction","z":"f80624abfd69b02e","x":2080,"y":1220,"wires":[["cbdcfc6a2166b7ee","b04429265d510afe","f977fa12fa24d0e9","4936b7f3448d30e8","2394c0ef8e1b0431"]]},{"id":"d8d5ce268004b131","type":"ui-group","name":"Dynamic Demo","page":"1525cc4810388af6","width":"12","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"1525cc4810388af6","type":"ui-page","name":"Dynamic Demo","ui":"22ea43815413e748","path":"/mssql","icon":"home","layout":"grid","theme":"c2ff5ba1f92a0f0e","order":1,"className":"","visible":"true","disabled":"false"},{"id":"22ea43815413e748","type":"ui-base","name":"base","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"showPageTitle":true,"navigationStyle":"default","titleBarStyle":"default"},{"id":"c2ff5ba1f92a0f0e","type":"ui-theme","name":"Default","colors":{"surface":"#ffffff","primary":"#813b5a","bgPage":"#beacac","groupBg":"#ffffff","groupOutline":"#cc2828"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px","density":"default"}}]
```

2024-09-11 11:46 UTC, gayanSandamal commented
> Enforcing the `controlVariant` to be stacked too isn't friendly for touchscreens, so please make this a configurable option for the Number Input itself

I discussed with @Steve-Mcl last week and provided this stacked control view as the native input type["number"] has this stacked layout by default and the input area got covered by the controllers on 1x1 size.

But as you mentioned it's not user friendly for touchscreens. I will add this as a configuration and also mention that the "_stacked layout is recommended for smaller grid sizes_"

2024-09-11 11:52 UTC, gayanSandamal commented
> Additional issues...
> 
> 1. Setting a negative step permits number to escape bounds (top number input in demo gif)
>    
>    1. Result is unpredictable. Either we support negative spin or add validation
>    2. Operating the spinner button permits the value to escape min/max
> 2. In some cases, operating keyboard up/down not possible (think it is related to step > 1, not sure)
> 3. In some cases, the spinner buoon is greyed out (see 4th spinner in gif) - max is 100 but spinner button is greyed
> 
> **IMPORTANT CLUE** After injecting dynamic values for all props, everything appears to work correctly (except negative step)

Thanks @Steve-Mcl for the detailed feedback! I’ll investigate with the NR dashboard flow given and fix the issues you pointed and the remaining edge cases as well.

2024-09-12 08:13 UTC, gayanSandamal commented
> Enforcing the `controlVariant` to be stacked too isn't friendly for touchscreens, so please make this a configurable option for the Number Input itself

Added a new property called "Spinner" by giving the default value as "Inline" which is touch screen friendly
<img width="366" alt="Screenshot 2024-09-12 at 13 27 25" src="https://github.com/user-attachments/assets/11e6737b-667e-4625-b740-3fedf9031bd9">

But it will lead to this cluttered layout in 1x1 grid size
<img src="https://github.com/user-attachments/assets/c5f73260-4760-4ab9-97f5-bb3e61503e30" width="300" />

Therefore the user can change the spinner type to "Stacked" if necessary
<img src="https://github.com/user-attachments/assets/21d954b7-83b3-48e8-aec4-c3a1b4e331ce" width="300" />

2024-09-12 09:22 UTC, gayanSandamal commented
> Additional issues...
> 
> 1. Setting a negative step permits number to escape bounds (top number input in demo gif)
>    
>    1. Result is unpredictable. Either we support negative spin or add validation
>    2. Operating the spinner button permits the value to escape min/max
> 2. In some cases, operating keyboard up/down not possible (think it is related to step > 1, not sure)
> 3. In some cases, the spinner buoon is greyed out (see 4th spinner in gif) - max is 100 but spinner button is greyed
> 
> **IMPORTANT CLUE** After injecting dynamic values for all props, everything appears to work correctly (except negative step)
> 
> Demo: ![chrome_dxBwBqVafK](https://private-user-images.githubusercontent.com/44235289/366428457-2faeb6a6-bdb0-48df-b42f-a930edcd02ef.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjkxMTcsIm5iZiI6MTcyNjEyODgxNywicGF0aCI6Ii80NDIzNTI4OS8zNjY0Mjg0NTctMmZhZWI2YTYtYmRiMC00OGRmLWI0MmYtYTkzMGVkY2QwMmVmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTJlNTIxN2VlNTY5OTNkMGQzYjJiMTY3N2Q2NTRjNjFmZDljMmUxNDExMzA0MzI0YjJlZjM0Njk5MDNjYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDXnFfG6t0jTvQRqH_VH2R-EYCzDOjxxY2xnGsV-Jns) [ ![chrome_dxBwBqVafK](https://private-user-images.githubusercontent.com/44235289/366428457-2faeb6a6-bdb0-48df-b42f-a930edcd02ef.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjkxMTcsIm5iZiI6MTcyNjEyODgxNywicGF0aCI6Ii80NDIzNTI4OS8zNjY0Mjg0NTctMmZhZWI2YTYtYmRiMC00OGRmLWI0MmYtYTkzMGVkY2QwMmVmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTJlNTIxN2VlNTY5OTNkMGQzYjJiMTY3N2Q2NTRjNjFmZDljMmUxNDExMzA0MzI0YjJlZjM0Njk5MDNjYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDXnFfG6t0jTvQRqH_VH2R-EYCzDOjxxY2xnGsV-Jns) ](https://private-user-images.githubusercontent.com/44235289/366428457-2faeb6a6-bdb0-48df-b42f-a930edcd02ef.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjkxMTcsIm5iZiI6MTcyNjEyODgxNywicGF0aCI6Ii80NDIzNTI4OS8zNjY0Mjg0NTctMmZhZWI2YTYtYmRiMC00OGRmLWI0MmYtYTkzMGVkY2QwMmVmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTJlNTIxN2VlNTY5OTNkMGQzYjJiMTY3N2Q2NTRjNjFmZDljMmUxNDExMzA0MzI0YjJlZjM0Njk5MDNjYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDXnFfG6t0jTvQRqH_VH2R-EYCzDOjxxY2xnGsV-Jns) [ ](https://private-user-images.githubusercontent.com/44235289/366428457-2faeb6a6-bdb0-48df-b42f-a930edcd02ef.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjkxMTcsIm5iZiI6MTcyNjEyODgxNywicGF0aCI6Ii80NDIzNTI4OS8zNjY0Mjg0NTctMmZhZWI2YTYtYmRiMC00OGRmLWI0MmYtYTkzMGVkY2QwMmVmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTJlNTIxN2VlNTY5OTNkMGQzYjJiMTY3N2Q2NTRjNjFmZDljMmUxNDExMzA0MzI0YjJlZjM0Njk5MDNjYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDXnFfG6t0jTvQRqH_VH2R-EYCzDOjxxY2xnGsV-Jns)
> 
> Demo flow:
> 
> ```
> [{"id":"cbdcfc6a2166b7ee","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"auto, min:0, max:10, step 1","order":14,"width":0,"height":0,"topic":"topic","topicType":"msg","min":0,"max":10,"step":1,"tooltip":"","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":false,"icon":"","iconPosition":"left","iconInnerPosition":"inside","x":2280,"y":1200,"wires":[[]]},{"id":"b04429265d510afe","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"2x1, min 0, max 10, step 1","order":16,"width":"2","height":"1","topic":"topic","topicType":"msg","min":0,"max":10,"step":1,"tooltip":"","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":false,"icon":"","iconPosition":"left","iconInnerPosition":"inside","x":2280,"y":1240,"wires":[[]]},{"id":"f977fa12fa24d0e9","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"6x1, min 0, max 9, step 3, icon+tooltip+clear","order":13,"width":"6","height":"1","topic":"topic","topicType":"msg","min":0,"max":"9","step":"3","tooltip":"6x1, min 0, max 9, step 3, icon+tooltip+clear","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":true,"icon":"cog","iconPosition":"left","iconInnerPosition":"inside","x":2330,"y":1280,"wires":[[]]},{"id":"4936b7f3448d30e8","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"6x1, min 0, max 15, step -5, icon+tooltip+clear","order":12,"width":"6","height":"1","topic":"topic","topicType":"msg","min":0,"max":"15","step":"-5","tooltip":"6x1, min 0, max 15, step -5, icon+tooltip+clear","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":true,"icon":"home","iconPosition":"left","iconInnerPosition":"outside","x":2340,"y":1320,"wires":[[]]},{"id":"bc628c01a00bc840","type":"inject","z":"f80624abfd69b02e","name":"dynamic","props":[{"p":"ui_update.step","v":"2","vt":"num"},{"p":"ui_update.min","v":"4","vt":"num"},{"p":"ui_update.max","v":"8","vt":"num"},{"p":"ui_update.icon","v":"check","vt":"str"},{"p":"ui_update.label","v":"fred","vt":"str"},{"p":"ui_update.clearable","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1960,"y":1220,"wires":[["c68b54d25a2dd6c8"]]},{"id":"c5c577944d07723b","type":"inject","z":"f80624abfd69b02e","name":"reset dynamic","props":[{"p":"ui_update.step","v":"null","vt":"json"},{"p":"ui_update.min","v":"null","vt":"json"},{"p":"ui_update.max","v":"null","vt":"json"},{"p":"ui_update.icon","v":"null","vt":"json"},{"p":"ui_update.label","v":"null","vt":"json"},{"p":"ui_update.clearable","v":"null","vt":"json"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1986,"y":1302,"wires":[["c68b54d25a2dd6c8"]]},{"id":"2394c0ef8e1b0431","type":"ui-number-input","z":"f80624abfd69b02e","group":"d8d5ce268004b131","name":"","label":"auto, min 0, max 100, step 1","order":15,"width":0,"height":0,"topic":"topic","topicType":"msg","min":0,"max":"100","step":"1","tooltip":"Hello tooltip","passthru":true,"sendOnBlur":true,"sendOnEnter":true,"className":"","clearable":false,"icon":"","iconPosition":"left","iconInnerPosition":"inside","x":2280,"y":1380,"wires":[[]]},{"id":"c68b54d25a2dd6c8","type":"junction","z":"f80624abfd69b02e","x":2080,"y":1220,"wires":[["cbdcfc6a2166b7ee","b04429265d510afe","f977fa12fa24d0e9","4936b7f3448d30e8","2394c0ef8e1b0431"]]},{"id":"d8d5ce268004b131","type":"ui-group","name":"Dynamic Demo","page":"1525cc4810388af6","width":"12","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"1525cc4810388af6","type":"ui-page","name":"Dynamic Demo","ui":"22ea43815413e748","path":"/mssql","icon":"home","layout":"grid","theme":"c2ff5ba1f92a0f0e","order":1,"className":"","visible":"true","disabled":"false"},{"id":"22ea43815413e748","type":"ui-base","name":"base","path":"/dashboard","includeClie [...]

2024-09-12 09:35 UTC, gayanSandamal commented
> <img alt="Screenshot 2024-09-11 at 11 50 29" width="537" src="https://private-user-images.githubusercontent.com/99246719/366423694-b8191b4d-b170-468e-bd84-63f177a18722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjkxMTcsIm5iZiI6MTcyNjEyODgxNywicGF0aCI6Ii85OTI0NjcxOS8zNjY0MjM2OTQtYjgxOTFiNGQtYjE3MC00NjhlLWJkODQtNjNmMTc3YTE4NzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMTk5ZWM0NzcyNGUxZGFkOTU0NzQxY2FlMjkyNDMzNzFjMGE2ZDlkNDYyZTA5NjYzMGJkMWNmODYxMzdkM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSe5N5PlYPgYmJSlR9oW9Mmf37P9c4wXOwJnZKblynM">
> Tried setting the step and min/max and get errors, only the last error here is relevant

This is also handled with https://github.com/FlowFuse/node-red-dashboard/pull/1273/commits/cec107c7221e5d502d35647a33fe833c7bb8e119

2024-09-14 12:10 UTC, gayanSandamal commented
> @gayanSandamal does this mean that you consider this is now ready for re-review?

@joepavitt Yes, this is ready for review

2024-09-16 09:47 UTC, joepavitt approved these changes

2024-09-16 10:02 UTC, joepavitt commented
Have gone through all of the comments and feedback here, and as far as I can tell, it's all working as planned.

2024-09-16 10:02 UTC, merged