Add msg support for y axis type
FlowFuse/node-red-dashboard pull request #1325
Opened 2024-09-24 20:10 UTC by Steve-Mcl

closes #1253

## Description

### adds
* support for y-axis `key` and `msg.` (could not think how `str` would work!

### fixes 

* fixes x-axis `msg.xxx` evaluation. Previously it was using the simple `getProperty` and trying to get msg.payload.payload.x now it uses the RED util function to correctly evaluate the prop

* y-axis not being hidden when series is set to JSON type

* string type for x-axis not working as expected
  * e.g. on < v1.17.0, import the bar chart example and set the x-axis to string "USA" - we get a timestamp number

* line chart example
  * was configured to use `msg.datestamp`
  * now that evaluating `msg.` is fixed, this breaks the example (it was working by accident)

* scatter chart example 
  *  was configured to use `msg.x` but now that evaluating `msg.` is fixed, this breaks the example (it was working by accident)

* bar chart example: 
  * is configured to use `msg.category` (should really be  `key: category`)
  * now that evaluating `msg.` is fixed, this breaks the example (it was working by accident)

* Other
  * included a Clear inject on all three examples (save questions on the forum)
  * remove duplicate payload+datapoint merges when processing an array of points

## Related Issue(s)

#1253

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-09-25 08:26 UTC, Steve-Mcl commented
switching to draft until I can add "before tests" - want to ensure no breaking changes (apart from where something is fixed)

2024-10-04 12:38 UTC, joepavitt requested changes
Details left in comment above

2024-10-04 12:44 UTC, Steve-Mcl commented
your demo flow works perfect for me

![image](https://github.com/user-attachments/assets/88064c62-7e8b-45b7-949f-a814f017d467)

2024-10-04 12:47 UTC, joepavitt commented
<img width="450" alt="Screenshot 2024-10-04 at 13 46 47" src="https://github.com/user-attachments/assets/985be51c-bdba-4ba9-929b-aaca02c95183">

Hmmm.... I see these errors in the NR Debug Panel. Definitely running your branch, and have re-built, restarted, etc.

2024-10-04 12:57 UTC, Steve-Mcl commented
> <img alt="Screenshot 2024-10-04 at 13 46 47" width="450" src="https://private-user-images.githubusercontent.com/99246719/373642424-985be51c-bdba-4ba9-929b-aaca02c95183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDY5MzYsIm5iZiI6MTcyODA0NjYzNiwicGF0aCI6Ii85OTI0NjcxOS8zNzM2NDI0MjQtOTg1YmU1MWMtYmRiYS00YmE5LTkyOWItYWFjYTAyYzk1MTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEyNTcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZGFkNWYxZTk0NDk4MzM1OGMyZmRhZmRjZDYyOTM3NjMzZWUyNjljOTcyYzE3OGZlMjg0NzhkNTMzYTE0N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vpx15OIsx8CON37VKl_jIvpOkP2XqLfy3E6udljfDP4">
> Hmmm.... I see these errors in the NR Debug Panel. Definitely running your branch, and have re-built, restarted, etc.

Weird. I'm looking now

I'd like get this merged today if possible.

2024-10-04 13:02 UTC, joepavitt commented
Ah, my fault, the example I shared is broken, it should have marked the y property as `key: y`, and it did not.

2024-10-04 13:03 UTC, joepavitt approved these changes

2024-10-04 13:03 UTC, Steve-Mcl commented
> Ah, my fault, the example I shared is broken (did you change it to get it working?), it should have marked the y property as `key: y`, and it did not.

I changed the examples in the examples folder (as noted in the OP) because they were wrongly setting `msg.y` as the property. They only worked by accident because we never evaluated the msg props for the y axis.

2024-10-04 13:03 UTC, merged

2024-10-04 13:06 UTC, Steve-Mcl commented
> Ah, my fault, the example I shared is broken (did you change it to get it working?)

Re-read - no i didnt, but i did open it and "look" at its config.

I'll try once more, plain import and deploy...

2024-10-04 13:08 UTC, Steve-Mcl commented
> > Ah, my fault, the example I shared is broken (did you change it to get it working?)
> 
> Re-read - no i didnt, but i did open it and "look" at its config.
> 
> I'll try once more, plain import and deploy...

All good

![chrome_DojkwGuEk5](https://github.com/user-attachments/assets/71fe115e-423c-4919-be21-22a2a7c76090)