Missing data after reconnect
FlowFuse/node-red-dashboard pull request #1343
Opened 2024-09-29 09:28 UTC by Steve-Mcl

closes #1297

## Description

Watches for re-connection in the data tracker and re-sends `widget-load` upon detecting reconnection.

NOTE: I found a bug in current dashboard that multiplies the handlers everytime a different page is visitied.  This Pr completely refactors the event hook up so that ALL (and only the widgets associated handlers) are properly and always cleaned up. 

## Related Issue(s)

 #1297
## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-09-29 16:26 UTC, Steve-Mcl commented
Some good news. @colinl has tried this out against related issues & confirmed it

https://github.com/FlowFuse/node-red-dashboard/issues/1297#issuecomment-2381352730

2024-09-29 16:44 UTC, colinl commented
In fact I meant to post that here rather than against the issue.

2024-10-01 12:38 UTC, joepavitt requested changes

2024-10-01 12:38 UTC, joepavitt commented on ui/src/widgets/data-tracker.mjs
> +        // console.log('widget-load::msg-input:' + widgetId, msg, state)
```suggestion
```

2024-10-01 12:38 UTC, joepavitt commented on ui/src/widgets/data-tracker.mjs
> +        // console.log('data-tracker::msg-input:' + widgetId, msg)
```suggestion
```

2024-10-01 12:38 UTC, joepavitt commented on ui/src/widgets/data-tracker.mjs
> +        console.log('socket connect detected in data-tracker' + (emitWidgetLoadOnConnect ? ', emitting widget-load' : ''))
```suggestion
```

2024-10-01 12:38 UTC, joepavitt commented on ui/src/widgets/data-tracker.mjs
> +        console.log('socket disconnect detected in data-tracker, setting doReconnectSendWidgetLoad to true')
```suggestion
```

2024-10-04 13:17 UTC, joepavitt commented on ui/src/widgets/data-tracker.mjs
> +        if (emitWidgetLoadOnConnect) {
```suggestion
        // when we unexpectedly disconnect, this is set to true
        if (emitWidgetLoadOnConnect) {
```

2024-10-04 13:18 UTC, joepavitt approved these changes
Added a single line comment just as it took me a few reads to follow, but this is great. Thanks @Steve-Mcl

2024-10-04 13:18 UTC, merged