Support key type option in ui-table for entering fixed strings as item labels
FlowFuse/node-red-dashboard pull request #1349
Opened 2024-09-30 15:27 UTC by Steve-Mcl

closes #1188

## Description

* Alters "key" field to "value" and changes it to a typed input
  * fall back is type "key" (for backwards compatibility
* Adds e2e tests to ensure value rendered obeys `keyType` 

![chrome_uthk6yoxbC](https://github.com/user-attachments/assets/12ee2db6-298f-4d72-ac3b-1c142bce5b10)

## Related Issue(s)

#1188

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-10-01 12:34 UTC, joepavitt commented
Functionally, great, but I'm not convinced on the "key" icon. Few reasons:

1. `key` icon to me speaks security key
2. `key` as an icon to refer to the key of an object may not translate well into other languages.
3. If we're to be consistent with the `chart` node, it should just be the text "key"

2024-10-01 12:38 UTC, joepavitt reviewed
Functionally, great, but I'm not convinced on the "key" icon. Few reasons:

1. key icon to me speaks security key
2. key as an icon to refer to the key of an object may not translate well into other languages.
3. If we're to be consistent with the chart node, it should just be the text "key"

2024-10-01 16:30 UTC, Steve-Mcl commented
Removed key icon

2024-10-02 10:14 UTC, Steve-Mcl commented
Tests are passing. Failure is the usual:

```
  1) Node-RED Dashboard 2.0 - Control - Enable/Disable
       can enable/disable a particular page from the navigation options:
     AssertionError: Timed out retrying after 4000ms: expected '<a.v-list-item.v-list-item--link.v-list-item--nav.v-theme--nrdb.v-list-item--density-default.v-list-item--one-line.v-list-item--rounded.v-list-item--variant-text>' to have class 'v-list-item--disabled'
      at Context.eval (webpack://@flowfuse/node-red-dashboard/./cypress/tests/widgets/control.spec.js:137:51)
```

NOTE: Ideally we would fix this but for the time being, can we either disable this test or move the control tests to their own npm script and GH task so that we get clear passes on the other tests?

2024-10-04 12:21 UTC, joepavitt requested changes

2024-10-04 12:21 UTC, joepavitt commented on nodes/widgets/ui_table.html
> +                    console.log('ui-table: setting up typedInput for key')
```suggestion
```

2024-10-04 12:23 UTC, joepavitt approved these changes

2024-10-04 12:23 UTC, merged