Add PWA Functionality
FlowFuse/node-red-dashboard pull request #708
Opened 2024-03-25 02:05 UTC by cgjgh

## Description

Integrate PWA functionality with Vite-PWA, which includes a service worker, is installable across platforms such as Windows, iOS, and Android, implements caching with automatic updates, and cleans up outdated caches, and features automatic switching of the status bar between light and dark modes.

## Related Issue(s)

[https://github.com/FlowFuse/node-red-dashboard/issues/88](url)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass --No tests added-minimal changes
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-03-25 05:48 UTC, bartbutenaers commented
Hi @cgjgh,
Thanks for this PR!

Recently I wanted to create a shortcut to my flowforge dashboard D2 on my Android smartphone, but there was no *"Add to home screen"* menu option available in Chrome.  After some searching the reason seemed to be that dashboard D2 was not a PWA...

Very useful PR!
Bart

2024-03-25 08:04 UTC, colinl commented
I believe the Add to Homescreen capability was added a few weeks ago. It certainly now works for me.

2024-03-25 12:21 UTC, cgjgh commented
Add to Home Screen option was available on iOS at least, but seemed to only make a web shortcut which ran in a full screen browser. No caching or background worker which could now be used to receive push notifications for instance. 

Also I’ve frequently gotten blank white screens on launch which lasted until Safari browser cache was cleared. This pull request fixes issue.

Also Dashboard logo did not appear on installed app icon,  now present in iOS, Windows and Android.

2024-03-25 13:29 UTC, bartbutenaers commented
> background worker which could now be used to receive push notifications for instance

@cgjgh 
Thanks for the clarification!
Don't want to go off-topic, but I am not really familiar with PWA.
I would appreciate if you could add some feedback about push notifications to this [issue](https://github.com/FlowFuse/node-red-dashboard/issues/589).  I have about 99% of my web-push ui node completed (also by registering a service worker in my own custom ui node).  But now I am a bit confused whether you mean (native) push notifications or web push notifications, why you need pwa for a service worker, and so on.  Would love to hear your thoughts in that other issue.
Thanks!!!

2024-03-25 19:20 UTC, cgjgh commented
@bartbutenaers 
> But now I am a bit confused whether you mean (native) push notifications or web push notifications,

To clarify, notifications from a PWA will show up as native device push notifications, originating from and linking to PWA app, which will have its own icon and window instead of browser’s.

> why you need pwa for a service worker,

As I understand service workers are not exclusive to PWAs, but rather PWAs build on top of them. PWA can also work offline, not relevant in the case of Node Red, but can help with caching to improve launch speed, providing a more native app feel. As such, they support various native functionality such as push notifications, badges on PWA icon, geolocation, biometric authentication, etc, features that are more heavily restricted on iOS requiring web app to be installed as a PWA.

[Example PWA - test notifications](https://whatpwacando.today/)

### References
[Making PWAs Installable](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable)

[Caching](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Caching)

[Notifications and Push API Example](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push)

### Example Notification on lock screen
![IMG_2438](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/bb71d1f3-3fcb-4bbf-a53e-9eac429d6d95)
### Badges on home screen icon
![IMG_2439](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/97a497a7-a167-4c21-ab37-7426dbe2dd3c)
### PWA notification settings in iOS settings
![IMG_2443](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/839cc475-8428-4b62-8afe-368e07985661)

2024-03-25 20:25 UTC, bartbutenaers commented
Thanks!!
Features like Geolocation, ... are of course very useful features for home automation.
I will mention you in the other issue focussed on push notifications, because I don't want to hijack your PR discussion.

2024-03-26 08:55 UTC, joepavitt requested changes
Firstly, thanks for the PR! Really appreciate the contribution, and keen to get this merged asap.

**Feedback:**
- We seem to be missing a `package-lock.json` from your dependency updates, which is preventing the automated build through our GH actions?
- I've installed locally, and run our tests and there are many failures, but will need to investigate in more detail in order to understand the causes. With your local deployment, please do run `npm run cy:run` in order to run our E2E tests and ensure no regressions/problems are introduced.

2024-03-26 13:40 UTC, cgjgh commented on ui/public/apple-touch-icon.png
Apple does not allow Home Screen icons to be transparent. If they are, it will automatically apply a black background. This causes a flickering transition from transparent to black every time app is exited to Home Screen. I can change it to instead use the generated [apple-touch-icon-180x180](https://github.com/FlowFuse/node-red-dashboard/pull/708/files/6b45f86b3d828748acd3ef557925cae8d508174c#diff-ab6f9600398cf945fad96fb538a9af77038e25ddda1d662fa456c507fa0e0998) with white background if you prefer.

2024-03-26 13:45 UTC, cgjgh commented
I will look into the above errors later today, think some updated files were not added to commit.

2024-03-26 15:55 UTC, joepavitt commented on ui/public/apple-touch-icon.png
Let's go for the white background so it's consistent :+1:

2024-03-28 09:31 UTC, joepavitt commented
The E2E Tests are now failing here in line with how they failed when I run locally. Cypress required an on `load` event to be fired from the page to determine that the UI has updated after a page navigation, _something_ in these changes is preventing that event from firing.

2024-04-05 14:15 UTC, fencer commented
is there a plan when this will be released? looking forward for this functionality.

2024-04-05 15:15 UTC, joepavitt commented
> is there a plan when this will be released? looking forward for this functionality.

One the E2E tests pass - waiting on @cgjgh to take a look. The service worker introduced is preventing the `onLoad` event firing from the browser currently.

2024-04-06 01:56 UTC, cgjgh reviewed
Changes made, ready for further review.

2024-04-06 02:07 UTC, cgjgh commented
Load event not firing seems to be an ongoing issue with service workers and Cypress as can be seen here: [https://github.com/cypress-io/cypress/issues/27501](https://github.com/cypress-io/cypress/issues/27501). 

For now the only solution seems to be to disable service worker while testing in Cypress, which I've done by intercepting request for sw.js and returning empty object preventing it from registering:

` cy.intercept('/dashboard/sw.js', {
        body: undefined
    })`

Let me know whether you approve of this fix .

2024-04-06 06:56 UTC, joepavitt commented
Thanks @cgjgh - re running the tests action now, I'm away on vacation until Tuesday 16th, so can do a full and proper review then. 

Unless @Steve-Mcl or @sherbastian can take a look in the mean time - but no pressure to, as I'd still need to cut a release to make this available for all anyway

2024-04-19 02:30 UTC, cgjgh commented
@joepavitt Fixed, please try again. 
Sorry for all the inconveniences caused by all this back and forth.

2024-04-23 13:24 UTC, joepavitt approved these changes

2024-04-23 13:24 UTC, merged

2024-04-26 16:37 UTC, Paul-Reed commented
@cgjgh Nice work, it's a lot more resilient than 'Add to Home Screen'.
Thanks for submitting.

2024-04-28 02:22 UTC, cgjgh commented
@Paul-Reed Thanks for the feedback! May I ask what platform you're using? Haven't done any much testing on Android, just iOS and Windows. Wondering what the experience is there.

2024-04-28 03:56 UTC, bartbutenaers commented
@cgjgh 
I am not sure if you are following the Discourse forum, so mentioning you here.  There is a PWA related [question](https://discourse.nodered.org/t/is-this-a-side-effect-of-the-pwa-functionality).  Maybe it let ring some bells in your head...

2024-04-28 05:26 UTC, Steve-Mcl commented
@bartbutenaers it might be possible to add the pages as shortcuts in the manifest. 

Here is a good article: https://medium.com/going-fullstack/adding-shortcuts-to-progressive-web-apps-53e249b06aaf

2024-04-28 08:31 UTC, colinl commented
> it might be possible to add the pages as shortcuts in the manifest

For me the biggest problem is that it appears not to be possible in Android to rename the shortcut on the home page.  The result is, I presume, that I will not be able tell which shortcut is for which system.  Perhaps the app name could be provided via settings. js.  It might be good to be able to change the icon too.

2024-04-28 08:31 UTC, Paul-Reed commented
> @Paul-Reed May I ask what platform you're using? Haven't done any much testing on Android,  Wondering what the experience is there.

Android 14 on a Pixel 6.
The Node-RED server is Oracle cloud running Ubuntu 22.04.4.

It seems much more solid than the 'web shortcut', the data is up to date as soon as it's opened, and it is framed very nicely to fit the screen.

Don't know if the 'Server disconnected' popup is part of PWA, but it's a really useful addition, and gives me greater confidence to view my data.

Don't know it it's possible, but the NR icon does not look good (especially on a dark theme), can we use our own icons?

2024-04-28 08:34 UTC, joepavitt commented
Which version of Android are you on @colinl ? And which browser?

When I click "Add to Home Screen" I get presented with the option to name the shortcut

![SmartSelect_20240428_093339_Chrome.jpg](https://github.com/FlowFuse/node-red-dashboard/assets/99246719/4b9b46a1-34de-4bce-bc8b-6959c7e42678)

2024-04-28 08:36 UTC, joepavitt commented
> Don't know if the 'Server disconnected' popup is part of PWA, but it's a really useful addition

Separate addition that we put into `1.8.0`

For the icon, it's not configurable at the moment, but that's partly my fault as I asked @cgjgh to change it to white background as per other icons used, we can change the default

2024-04-28 08:48 UTC, Paul-Reed commented
> When I click "Add to Home Screen" I get presented with the option to name the shortcut

Joe that looks as though you are creating a web shortcut & not installing the app??
In fact, just to check, I deleted my 'app', cleared the phone cache, and tried to re add it, but the option to install the app is now missing from the context menu. Something has changed...

2024-04-28 09:04 UTC, colinl commented
> Which version of Android are you on @colinl ? And which browser?

Android version 14. Brave and Chrome browsers.  You should not be getting the Add to Home Screen any more, as @Paul-Reed says.  However, there seems to be something odd going on. I removed all my shortcuts and the installed web app and restarted the phone. Now, when I try to open the dashboard in either browser it just appears to hang with a blank screen. I do get the Install App option on the dropdown menu though.

2024-04-28 09:06 UTC, colinl commented
> I do get the Install App option on the dropdown menu though.

Unfortunately the app doesn't seem to work, I just get the blank screen! So for the moment I have no access at all.

2024-04-28 09:15 UTC, colinl commented
Hmm, not sure what is going on here. I think it may be to do with the fact that I am using Cloudflare ZeroTrust with Google Oauth access control. I think the reason that I was getting the blank page was that it was waiting for the authorisation. I have managed to get it working again, it will be interesting to see what happens the next time the auth times out and I need to login again with google acct.

2024-04-28 09:19 UTC, Paul-Reed commented
Still working ok here.

I add the app by selecting 'add to home screen' from the context menu, that then presents the 'install app' (like the screenshot above), and then get a confirmation pop-up that the app was successfully installed.
I've just repeated the process again.

2024-04-28 09:25 UTC, colinl commented
> Still working ok here.

On the home screen do you see the icon with the white surround, I was getting that, but now I am not, and although it says it is installing the app I am not conviced it is, it looks just like a shortcut.  If you hold down on the icon what options do you see?  The first time I installed it I had different options, but having cleared everything and starting again I just get the App Info and Remove options like a regular shortcut.

2024-04-28 09:32 UTC, Paul-Reed commented
> On the home screen do you see the icon with the white surround

Yes

> If you hold down on the icon what options do you see?

![Screenshot_20240428-103126.png](https://github.com/FlowFuse/node-red-dashboard/assets/973580/e512d9a7-19ed-4d98-9532-cbce1966c02b)

2024-04-28 09:51 UTC, joepavitt commented
> Joe that looks as though you are creating a web shortcut & not installing the app??
I believe that you should see this instead...

You're right, I am on `1.8.0` though, but accessing via local network - so maybe Chrome doesn't let me "install" it

2024-04-28 10:02 UTC, Steve-Mcl commented
> > Joe that looks as though you are creating a web shortcut & not installing the app??
> > I believe that you should see this instead...
> 
> You're right, I am on `1.8.0` though, but accessing via local network - so maybe Chrome doesn't let me "install" it

I believe it needs to be HTTPS. 

If you try from a FF instance, you should see "install app" for v1.8.0 and the add shortcut is no longer offered. 

That's why I suggested we could/should serve dynamic manifest with the pages offered as shortcuts. See previous comment. 

As well as shortcuts, the app name should be set by the base name or some other property in the users flows. That is because if you "install" more than one dashboard site as an app, all of your application names installed on your device will all be exactly the same.

2024-04-28 10:31 UTC, colinl commented
@Paul-Reed Does Site Settings let you edit the name and icon?

2024-04-28 10:34 UTC, Paul-Reed commented
> Does Site Settings let you edit the name and icon?

Unfortunately no, there is no option for either the name or icon.

2024-04-28 12:44 UTC, colinl commented
> Unfortunately no, there is no option for either the name or icon.

I asked because, at some point, I did see such an option, but I have since removed the app and now can't get it to install again. It asks if I want to install it and I say yes, but then it just comes up with the Add to Home screen options. I guess that the install is failing for some reason and it is dropping back to Add to Home Screen.  I am using https.

2024-04-28 12:58 UTC, Paul-Reed commented
Have you cleared your browser cache?


On Sun, 28 Apr 2024, 13:45 Colin Law, ***@***.***> wrote:

> Unfortunately no, there is no option for either the name or icon.
>
> I asked because, at some point, I did see such an option, but I have since
> removed the app and now can't get it to install again. It asks if I want to
> install it and I say yes, but then it just comes up with the Add to Home
> screen options. I guess that the install is failing for some reason and it
> is dropping back to Add to Home Screen. I am using https.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FlowFuse/node-red-dashboard/pull/708#issuecomment-2081473270>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHNWDGHZFUAIPC72ZH7DTDY7TVM7AVCNFSM6AAAAABFGGTG7GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBRGQ3TGMRXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-28 13:11 UTC, colinl commented
Yes, it didn't seem to help. I will have to steal one of the family's phones to see if it will install there.

2024-04-28 20:01 UTC, cgjgh commented
Not sure if this will help, but I had some strange behaviors with  version 1.8.0 as well, blank screens, etc. I updated to 1.8.1 and after uninstalling and clearing website data and cache seems to work well.

Also I tried installing Dashboard on two different Android 14 device emulators, Android 14 and 15 using both Chrome and Brave. All scenarios installed and didn't get any blank screens or anything, although I did notice that _Install App_ option was not always immediately available, and showed instead _Add to home screen_ which would just add a web shortcut. 

Also, I noticed that it had the Chrome icon as well on app icon which is inconsistent with PWA app icon behavior.
![Screenshot 2024-04-28 143032](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/e934d4ea-2616-4cf9-8f36-cd9e0624b773)

Chrome and Android versions:
![Screenshot 2024-04-28 144521](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/28fc3abe-af5b-47f2-a30b-fcf332cff7d9)


As for setting shortcut for which webpage to open, that's predetermined in the generated manifest file with `"start_url":"./" `,  so can not be changed when installing.

The option @Steve-Mcl mentioned could be a workaround for now, but if PWA functionality is to be retained, I'd suggest solving this in the future by changing path in ui-base config of Dashboard 2.0, which is currently in development I understand.
![Screenshot 2024-04-28 145549](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/381e74ca-1703-4142-9c23-4075e444570f)

2024-04-29 14:34 UTC, colinl commented
I think I have worked out what is going on with the blank screen I have been getting sometimes.
As I said earlier I use Google Oauth to authenticate and Cloudflare ZeroTrust.
Before the PWA capability, if re-authentication was required, reloading the page (by swiping down in Android) attempted to reload the dashboard and I was redirected to the Google login screen by Cloudflare so I could login and then the dashboard loaded.
Now, with the PWA version, if the authentication has expired then I just get a blank screen and there does not seem to be a way of forcing a reload so I am stuck.

To recover the situation I have to browse to the node-red root url (not the dashboard) and then I get the login screen before the editor opens. Then if I go back to the dashboard application it opens ok.

2024-04-29 15:56 UTC, TotallyInformation commented
It sounds like the client code needs to have something that picks up a 401 response code from a client request and triggers a standard redirect to an endpoint defined in the D2 config.

2024-04-29 20:25 UTC, colinl commented
I have added issue #817 to track this problem

2024-05-03 14:28 UTC, Paul-Reed commented
Is there a logic to which dashboard page is initially opened, when the 'app' is opened?
I thought it may be the page which is listed topmost in the dashboard layout config, but doesn't appear to be.

2024-05-03 16:03 UTC, colinl commented
Does it open the same one as if you open it in a PC browser window?  It does for me.  There is an issue #728 (not PWA related) saying that it does not necessarily open the one at the top of the list, but I have not confirmed that myself.

2024-05-03 20:04 UTC, Paul-Reed commented
> Does it open the same one as if you open it in a PC browser window?

Yes, maybe just a coincidence, but the page that it always opens by default is the first page that I created after installing DB2.