UI Button - Add dynamic properties for label, icon & iconPosition
FlowFuse/node-red-dashboard pull request #864
Opened 2024-05-15 16:21 UTC by joepavitt

## Description

- Adds `label`, `icon` and `iconPosition` dynamic properties
- Adds E2E coverage
- Updates documentation

## Related Issue(s)

Close #862 

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-05-16 10:13 UTC, Steve-Mcl requested changes
### comparisons to `undefined`
I recommend the use of `typeof x !== 'undefined'` - it is safer and is best practice

### Fallbacks dont consider user might want empty string labels
The code uses this pattern  `return this.dynamic.xxx || this.props.xxx` and `if (msg.xxx) { /* dynamic xxx, update the store */ }`. 
These will not permit a user to set an empty string e.g. a label of `""` is falsey and will default to `props.label`

### question
The old Node-RED pattern for dynamic variables is to provide them invisibly in  `msg` object properties. The unwritten rule was that that if the property has a value, the magic `msg` property is discarded (i.e. does not override the entered value)

The newer Node-RED pattern is to provide a visible means for setting dynamic properties via the `typedInput` control 

Neither of these patterns are observed in this PR - can you please explain?

2024-05-16 10:26 UTC, joepavitt commented
> The old Node-RED pattern for dynamic variables is to provide them invisibly in msg object properties. The unwritten rule was that that if the property has a value, the magic msg property is discarded (i.e. does not override the entered value)

I wasn't familiar with that, as far as I'm concerned, if a user has injected an override, it should override.

2024-05-16 10:47 UTC, joepavitt commented
> Comparisons to undefined
I recommend the use of typeof x !== 'undefined' - it is safer and is best practice

> Fallbacks dont consider user might want empty string labels
The code uses this pattern return this.dynamic.xxx || this.props.xxx and if (msg.xxx) { /* dynamic xxx, update the store */ }.
These will not permit a user to set an empty string e.g. a label of "" is falsey and will default to props.label

Addressed in 1feb92a8

2024-05-16 10:57 UTC, Steve-Mcl commented
> > The old Node-RED pattern for dynamic variables is to provide them invisibly in msg object properties. The unwritten rule was that that if the property has a value, the magic msg property is discarded (i.e. does not override the entered value)
> 
> I wasn't familiar with that, as far as I'm concerned, if a user has injected an override, it should override.

https://discourse.nodered.org/t/dynamic-input-for-range-node/3091/4?u=steve-mcl 


There are better explanations that the linked one above but I am fairly certain the reason was that it prevents stray properties a msg has picked up overriding "hard coded values a user has entered".  

As an alternative option, you may wish to consider a pattern that is less likely to fall foul of the above. Obviously that would be to use the typedInputs as per intended design but I understand the reluctance. Perhaps a more specific/less-common `msg` property specifically for property overrides could be employed by the `ui` nodes?  Something like `msg.ui.override.xxx` or `msg.uiProps.xxx` - something that is not so easy to be picked up by a message like `label`.  Alternatively, support a distinct but well formed message type with a specific topic "set-label" and `payload` containing the dynamic value.  This way, the widgets value part (what the payload normally used for) is NOT REQUIRED (i.e no need to delete msg.payload for only updating the label) 

These are just a couple of suggestions, it is, of course, your choice. Happy to discuss merits of alternative approaches that keep it simple but avoid pitfalls discussed above.

2024-05-29 09:56 UTC, Steve-Mcl commented on nodes/widgets/locales/en-US/ui_button.html
> +        <dd>Change which side of the label the icon renders</dd>
No mention of `msg.ui_control` - users will likely stumble here Joe.

In https://github.com/FlowFuse/node-red-dashboard/pull/861 you have added a comment above the dynamic properties to clarify this - see here: https://github.com/FlowFuse/node-red-dashboard/pull/861#discussion_r1618566423

2024-05-29 09:56 UTC, Steve-Mcl commented on nodes/widgets/locales/en-US/ui_button.html
>      <p>Any of the following can be appended to a <code>msg.</code> in order to override or set properties on this node at runtime.</p>
```suggestion
    <p>Any of the following can be appended to a <code>msg.ui_update</code> in order to override or set properties on this node at runtime.</p>
```

2024-05-29 10:00 UTC, Steve-Mcl commented on ui/src/widgets/ui-button/UIButton.vue
> +            }
```suggestion
            if (typeof updates.label !== 'undefined') {
                this.dynamic.label = updates.label
            }
            if (typeof updates.icon !== 'undefined') {
                this.dynamic.icon = updates.icon
            }
            if (typeof updates.iconPosition !== 'undefined') {
                this.dynamic.iconPosition = updates.iconPosition
            }
```

best practice.

2024-05-30 09:56 UTC, Steve-Mcl approved these changes

2024-05-30 10:51 UTC, merged