Add clearable and chips options to combobox
FlowFuse/node-red-dashboard pull request #953
Opened 2024-06-11 06:21 UTC by github-cyprien

## Description

Just add two small options for my needs (can see it on https://vuetifyjs.com/en/components/combobox/)
If you think this overloads the form, it's no problem not to accept it.

2024-06-11 09:48 UTC, joepavitt requested changes
This is great @github-cyprien - thanks for the PR.

Only a small request, could you also add the new options to the documentation please? 

Source for our online docs live in: `docs/nodes/widgets/ui-dropdown.md`

2024-06-11 12:47 UTC, github-cyprien commented
I see that these props are not dynamic, do you prefer i change that ?

2024-06-11 21:00 UTC, github-cyprien commented
I've add documentation and also a screenshot with new options...

2024-06-12 07:43 UTC, joepavitt approved these changes

2024-06-12 07:43 UTC, merged